import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['getting-started', 'motivation'],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/basic-usage',
        'guides/merge-strategies',
        'guides/multiple-contexts',
        'guides/middleware',
        'guides/error-handling',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: ['advanced/typescript', 'advanced/performance'],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: ['api/create', 'api/provider', 'api/from', 'api/types'],
    },
  ],
};

export default sidebars;
