name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      # Add testing when you're ready to implement tests
      # - name: Test
      #   run: pnpm test

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Build Docs
        run: pnpm docs:build
